name: home_cure
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.3.0
  auto_route: ^4.2.1
  awesome_notifications: ^0.6.21
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  file_picker: ^5.0.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^4.4.1+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.1.0
  flutter_svg: ^1.1.1+1
  flutter_webview_plugin:
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.0
  google_sign_in: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  overlay_support: ^2.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  syncfusion_flutter_datepicker: ^20.2.40
  syncfusion_flutter_pdfviewer: ^20.2.43-beta
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Avatar-02.png"

  # image_path: "assets/img/Logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/img/All-logo versions-02.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/img/
    - assets/svg/
    - assets/drawer_icons/

  fonts:
    - family: "Segoe UI"
      fonts:
        - asset: "assets/fonts/Segoe UI.ttf"
    - family: "Oswald"
      fonts:
        - asset: "assets/fonts/Oswald-Medium.ttf"
    - family: "Cairo"
      fonts:
        - asset: "assets/fonts/Cairo-Medium.ttf"
        - asset: "assets/fonts/Cairo-Black.ttf"
        - asset: "assets/fonts/Cairo-Bold.ttf"
        - asset: "assets/fonts/Cairo-ExtraBold.ttf"
        - asset: "assets/fonts/Cairo-ExtraLight.ttf"
        - asset: "assets/fonts/Cairo-Regular.ttf"
        - asset: "assets/fonts/Cairo-SemiBold.ttf"

flutter_gen:
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

  # Optional
  integrations:
    flutter_svg: true
